# Generated by Django 2.1.7 on 2019-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_review_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_close',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
