# Generated by Django 2.1.7 on 2019-04-28 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20190424_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_surname', models.CharField(max_length=100)),
                ('member_phone', models.CharField(max_length=10)),
                ('member_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
