# Generated by Django 2.1.7 on 2019-04-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190424_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('del_shop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polls.ShopArea'),
            preserve_default=False,
        ),
    ]
