# Generated by Django 2.1.7 on 2019-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoparea',
            name='isBooking',
            field=models.BooleanField(default=False),
        ),
    ]
