# Generated by Django 2.1.7 on 2019-05-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_shoparea_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoparea',
            name='approve_status',
            field=models.CharField(choices=[('รอการอนุมัติ', 'รอการอนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], default='รอการอนุมัติ', max_length=12),
        ),
    ]
