# Generated by Django 2.1.7 on 2019-05-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20190504_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(null=True)),
                ('event_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('รอตรวจสอบ', 'รอตรวจสอบ'), ('จ่ายแล้ว', 'จ่ายแล้ว'), ('ค้างชำระ', 'ค้างชำระ')], default='รอตรวจสอบ', max_length=100)),
                ('payment_price', models.IntegerField(default=0)),
                ('payment_date', models.DateField(null=True)),
                ('payment_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Shop')),
                ('user_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Zone'),
        ),
    ]
