# Generated by Django 2.1.7 on 2019-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
